"""
Tina Decision Logger
====================
Generate complete decision report after each autonomous decision.

Author: Tina AI
Date: 2026-05-02
"""

import os
import json
import datetime
from pathlib import Path

WORKSPACE = Path("C:/Users/USER/.openclaw/workspace")
TINA_ROOT = WORKSPACE / "Tina_Quant_System"
REPORTS_DIR = TINA_ROOT / "reports"
AUTONOMOUS_DIR = TINA_ROOT / "autonomous"


class DecisionLogger:
    """Autonomous decision log generator"""

    def __init__(self):
        REPORTS_DIR.mkdir(exist_ok=True)

    def generate_decision_report(self, decision_log):
        """Generate Markdown report from decision log"""
        timestamp = decision_log.get("timestamp", datetime.datetime.now().isoformat())
        trigger_reason = decision_log.get("trigger_reason", "Unknown")

        # Parse steps
        steps = decision_log.get("steps", [])
        analysis_step = self._find_step(steps, "analyze_5min_kline")
        rsi_step = self._find_step(steps, "recalculate_rsi_zones")
        script_step = self._find_step(steps, "create_new_strategy_script")
        bt_step = self._find_step(steps, "backtest_validation")

        # Get results
        analysis_result = analysis_step.get("result") if analysis_step else {}
        rsi_result = rsi_step.get("result") if rsi_step else {}
        bt_result = bt_step.get("result") if bt_step else {}
        final_decision = decision_log.get("final_decision", "unknown")

        max_loss = "N/A"
        if bt_result:
            max_loss = f"{bt_result.get('losses', 0)} losing trades"

        win_rate = bt_result.get("win_rate", "N/A") if bt_result else "N/A"
        profit_factor = bt_result.get("profit_factor", "N/A") if bt_result else "N/A"
        total_trades = bt_result.get("total_trades", 0) if bt_result else 0

        new_script = script_step.get("script", "") if script_step else ""
        script_name = Path(new_script).name if new_script else "N/A"

        old_entry_max = 65
        new_entry_max = rsi_result.get("entry_rsi_max", old_entry_max) if rsi_result else old_entry_max

        md = f"""# Tina Autonomous Decision Log

**Timestamp:** {timestamp}
**Trigger:** {trigger_reason}

---

## Trigger Conditions

- **Trigger type:** {trigger_reason}
- **Analysis target:** Last 3 days 5-min K-line data (2330)
- **Single max loss:** {max_loss}

---

## Analysis Process

### Step 1: Load Last 3 Days 5-Min K-line Data
- **K-line count:** {analysis_result.get('total_klines', 'N/A')} lines
- **RSI calculation range:** Last {len(analysis_result.get('rsi_values', []))} samples

### Step 2: Recalculate Optimal RSI Zones
- **Analysis date:** {rsi_result.get('analysis_date', 'N/A') if rsi_result else 'N/A'}
- **Best zone:** {rsi_result.get('best_zone', 'N/A') if rsi_result else 'N/A'}
- **New parameter suggestions:**
  - entry_rsi_min: **{rsi_result.get('entry_rsi_min', 'N/A')}**
  - entry_rsi_max: **{rsi_result.get('entry_rsi_max', 'N/A')}**
  - exit_rsi_min: **{rsi_result.get('exit_rsi_min', 'N/A')}**
  - exit_rsi_max: **{rsi_result.get('exit_rsi_max', 'N/A')}**

### Step 3: Create New Strategy Script
- **New script:** `{script_name}`
- **Location:** `strategies/`
- **Version:** {self._extract_version(script_name)}

### Step 4: Backtest Validation
- **Backtest period:** Last {total_trades} K-lines (simulated)
- **Win rate:** **{win_rate}%** {'[PASS]' if isinstance(win_rate, (int, float)) and win_rate > 55 else ''}
- **Profit factor:** **{profit_factor}** {'[PASS]' if isinstance(profit_factor, (int, float)) and profit_factor > 1.2 else ''}

---

## Execution Behavior

- **Script created:** `{script_name}`
- **Parameter update:** entry_rsi_max {old_entry_max} -> **{new_entry_max}**
- **Switch status:** {'[ACTIVE] New strategy activated' if final_decision == 'apply' else '[REJECTED] Backtest failed, notify Jo for manual intervention'}

---

## Decision Rationale

{'Auto-patch passed backtest, new strategy parameters applied.' if final_decision == 'apply' else 'Backtest failed threshold (win rate must be >55%, profit factor must be >1.2), maintaining current strategy and notifying Jo for manual intervention.'}

---

## Safety Rails Status

| Item | Status |
|:-----|:-------|
| main.py not modified | [OK] |
| New strategy saved as new file | [OK] |
| Backtest validation passed | {'[OK]' if final_decision == 'apply' else '[FAIL]'} |
| Jo notified | {'[PENDING]' if final_decision == 'reject' else '[N/A]'} |

---

*This report was automatically generated by Tina Autonomous Decision System | {timestamp}*
"""

        return md

    def _find_step(self, steps, step_name):
        for s in steps:
            if s.get("step") == step_name:
                return s
        return {}

    def _extract_version(self, script_name):
        try:
            parts = script_name.replace(".py", "").split("_")
            for p in parts:
                if p.startswith("v") and p[1:].isdigit():
                    return p
        except:
            pass
        return "?"

    def save_report(self, decision_log):
        """Save decision report to reports directory"""
        md_content = self.generate_decision_report(decision_log)

        date_str = datetime.date.today().isoformat()
        filename = f"tina_autonomous_decision_{date_str}.md"
        filepath = REPORTS_DIR / filename

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(md_content)

        print(f"[REPORT] Decision report saved: {filepath}")
        return filepath

    def save_quick_log(self, decision_log):
        """Save quick log (JSON) to autonomous directory"""
        log_path = AUTONOMOUS_DIR / f"decision_log_{datetime.date.today().isoformat()}.json"

        existing = []
        if log_path.exists():
            try:
                with open(log_path, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except:
                existing = []

        existing.append(decision_log)

        with open(log_path, "w", encoding="utf-8") as f:
            json.dump(existing, f, ensure_ascii=False, indent=2)

        return log_path


def main():
    logger = DecisionLogger()

    # Read latest decision_log
    today_log = AUTONOMOUS_DIR / f"decision_log_{datetime.date.today().isoformat()}.json"
    if today_log.exists():
        with open(today_log, "r", encoding="utf-8") as f:
            logs = json.load(f)
        if logs:
            latest = logs[-1]
            logger.save_report(latest)
    else:
        print("[INFO] No decision log today yet")


if __name__ == "__main__":
    main()